### ISSUE TITLE
Issue with Theo's Little Bot (Task number 2)

### ISSUE THREAD

**Issue by zezozzebezt** [theopolisme/theobot#3]
It flagged the file http://en.wikipedia.org/wiki/File:Bob_katsionis_imaginary_force.jpg as missing a description, but the description is there.. I don't understand.
Am I missing something, or is the bot malfunctioning?

**Comment by theopolisme** [comment]
When the bot tagged the file, it looked like [this](http://en.wikipedia.org/w/index.php?title=File:Bob_katsionis_imaginary_force.jpg&oldid=517773291)—as you can see, missing author details. This was then corrected by Sfan00 [here](http://en.wikipedia.org/w/index.php?title=File:Bob_katsionis_imaginary_force.jpg&direction=next&oldid=517773291)—but by the time the issue was corrected, you had already been notified.
